openapi: 3.0.0
info:
  description: "Ki Reply Assesment Test"
  version: "0.0.1"
  title: "Serenade"
  contact:
    email: "koushikjay66@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url : http://localhost:80

paths:
  /v2/sayhello:
    get:
      tags:
      - "sayhello"
      description: "Just Says Hello "
      operationId: "sayHelloReply"
      responses:
        "200":
          description: "Ok"
          
  /heartbeat:
    get:
      tags:
      - "heartbeat"
      description: "Returns Heartbeat"
      operationId: "heartbeat"
      responses:
        "200":
          description: "Ok"